interval: 3600  # Intervalo en segundos
websites:
  - url: "https://www.idl-reporteros.pe/feed/"
    type: "web"
  - url: "https://ojo-publico.com/rss.xml"
    type: "web"
  - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC5j8-2FT0ZMMBkmK72R4aeA"
    type: "youtube"
  - url: "https://www.bbc.com/mundo"
    type: "web"
  - url: "https://elcomercio.pe/"
    type: "web"
log_file: "app.log"
history_file: "history.json"
